[config]
schemaVersion = "0.0.1"

[package]
namespace = "skytech6"
name = "CrimsonHunt"
versionNumber = "0.1.0"
description = "Create battle-pass like rewards for V Blood hunting"
websiteUrl = "https://github.com/CrimsonMods/CrimsonHunt/"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.691.3"

[build]
icon = "./images/logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
communities = ["v-rising"]
repository = "https://thunderstore.io"
[publish.categories]
v-rising = ["1-0-update", "mods", "server"]